version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.api
    ports:
      - "8000:8000"

  shiny:
    build:
      context: .
      dockerfile: frontend/Dockerfile.shiny
    ports:
      - "3838:3838"
    depends_on:
      - api